### ISSUE TITLE
Prepare HLS-LL milestone tracker

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/HLS-LL#1]
### Description
Since HLS-LL is moving forward, we need to create a chart that tracks all of the milestones. It is expected to be a two year process from the initial LL investigation until HLS-LL is in production. However, we need a chart to track our progress so that we know the milestones but also stay on track.

[HLS-LL Milestone Tracker](https://docs.google.com/spreadsheets/d/1z0kS1ZCPSXNi0Xm0G0A9JeoCsdqqjxdtEHP-gbfQFD8/edit?gid=0#gid=0)
[HLS-LL Milestones](https://docs.google.com/document/d/1IX_IzxEW0_h-RNT8BDyJNeybIxoT28fewVB6lM0pKRA/edit)

### Acceptance Criteria
- [x] determine all milestones
- [ ] share milestones with stakeholders for approval (SNWG, HQ, etc.)
- [x] create milestone chart

**Comment by madhuksridhar** [comment]
next: revise the milestone chart with feedback from ATP DG:
* include timeframe to make the decision between Global vs on-demand
* include timeframe to make the decision between a new standalone HLS LL product vs converting current HLS to a LL version
